[package]
name = "zorsh-gen-example"
version = "0.1.0"
edition = "2021"

[[example]]
name = "simple_conversion"
path = "main.rs"

[dependencies]
anyhow = "1.0.96"
borsh = "1.5.5"
zorsh-gen-rs = { path = "../.." }
